# Generated by Django 4.2.11 on 2025-07-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_matchresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resume_file',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='matched_at',
        ),
        migrations.RemoveField(
            model_name='matchresult',
            name='matched_skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.TextField(help_text='Comma-separated list of required skills'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
